# Site settings
title: Jonah Fried
email: jonahfriedmars@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description. (c) Jonah Fried 2015
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonahf.co.uk" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jonahfried

# Title image
title-image: placeholder
title-image-description: some text

# Build settings
markdown: kramdown
